/*
---- Copyright Start ----

This file is part of the OpenVectorFormatTools collection. This collection provides tools to facilitate the usage of the OpenVectorFormat.

Copyright (C) 2022 Digital-Production-Aachen

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

---- Copyright End ----
*/

///////////////////////////////////////////////////////////
//  Direction.cs
//  Implementation of the Enumeration Direction
//  Generated by Enterprise Architect
//  Created on:      09-Mai-2018 17:26:22
//  Original author: Dirks
///////////////////////////////////////////////////////////




namespace OpenVectorFormat.ILTFileReader
{
    public enum Direction : int {

		clockwise = 0,
		counterClockwise = 1,
		openLine = 2

	}//end Direction

}//end namespace OpenVectorFormat.ILTFileReader
