/*
---- Copyright Start ----

This file is part of the OpenVectorFormatTools collection. This collection provides tools to facilitate the usage of the OpenVectorFormat.

Copyright (C) 2024 Digital-Production-Aachen

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

---- Copyright End ----
*/

///////////////////////////////////////////////////////////
//  IPart.cs
//  Implementation of the Interface IPart
//  Generated by Enterprise Architect
//  Created on:      08-Mai-2018 17:55:36
//  Original author: Dirks
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace OpenVectorFormat.ILTFileReader {
    /// <summary>
    /// Identifier to allow more than one model information in one file. For every id used in the commands
    /// start polyline (short/long/ASCII) and start hatches (short/long/ASCII) there shall be one command
    /// $$LABEL. Each id causes the building-process to build a different part.
    /// </summary>
	public interface IPart  {

		int id{
			get;
		}

		string name{
			get;
		}
	}//end IPart

}//end namespace OpenVectorFormat.ILTFileReader
